begin;
do $$
declare owner_id uuid:=gen_random_uuid(); tenant uuid; second_tenant uuid; roper_id uuid:=gen_random_uuid(); other_roper uuid:=gen_random_uuid(); snapshot jsonb; job jsonb; p public.producers%rowtype; a public.platform_producer_accounts%rowtype; failed boolean;
begin
  insert into auth.users(id,email) values(owner_id,'lifecycle-owner@example.invalid');
  insert into public.platform_owners(user_id) values(owner_id);
  perform set_config('request.jwt.claim.sub',owner_id::text,true);
  perform set_config('request.jwt.claims','{"aal":"aal2"}',true);
  insert into public.producers(name,slug) values('Lifecycle Fixture','lifecycle-fixture') returning id into tenant;
  insert into public.producers(name,slug) values('Other Lifecycle Fixture','other-lifecycle-fixture') returning id into second_tenant;
  insert into public.ropers(id,first_name,last_name,phone) values(roper_id,'Export','Roper','2545550123'),(other_roper,'Other','Roper','2545550124');
  insert into public.memberships(producer_id,roper_id,member_number,status) values(tenant,roper_id,'321','active'),(second_tenant,other_roper,'999','active');
  snapshot:=public.platform_producer_export_snapshot(tenant);
  if jsonb_array_length(snapshot->'tables'->'memberships')<>1 or snapshot->'tables'->'memberships'->0->>'member_number'<>'321' then raise exception 'Tenant membership export wrong'; end if;
  if jsonb_array_length(snapshot->'tables'->'ropers')<>1 or snapshot->'tables'->'ropers'->0 ? 'auth_user_id' then raise exception 'Shared roper export leaked account linkage'; end if;
  if snapshot->'tables' ? 'platform_producer_notes' or snapshot->'tables' ? 'platform_producer_exports' or snapshot->'tables' ? 'roping_timing_sessions' then raise exception 'Private state exported'; end if;
  job:=public.start_platform_producer_export(tenant,'Producer migration backup');
  failed:=false;
  begin perform public.start_platform_producer_export(tenant,'Second concurrent export'); exception when others then failed:=true; end;
  if not failed then raise exception 'Concurrent export allowed'; end if;
  perform public.finish_platform_producer_export((job->>'id')::uuid,false);
  if not exists(select 1 from public.platform_producer_exports where id=(job->>'id')::uuid and status='failed') then raise exception 'Failure not recorded'; end if;
  insert into public.events(producer_id,title,slug,starts_at,publication_state,is_public) values(tenant,'Public Fixture','public-fixture',now(),'published',true);
  select * into p from public.producers where id=tenant;
  select * into a from public.platform_producer_accounts where producer_id=tenant;
  failed:=false;
  begin perform public.manage_platform_producer(tenant,'account',jsonb_build_object('status','archived','reason','Archive test account','confirmed',true,'expectedUpdatedAt',a.updated_at)); exception when others then failed:=true; end;
  if not failed then raise exception 'Archive omitted visibility decision'; end if;
  perform public.manage_platform_producer(tenant,'account',jsonb_build_object('status','archived','reason','Archive test account','confirmed',true,'expectedUpdatedAt',a.updated_at,'archiveHideEvents',true));
  if exists(select 1 from public.events where producer_id=tenant and (publication_state='published' or is_public)) then raise exception 'Archive did not hide events'; end if;
  select * into a from public.platform_producer_accounts where producer_id=tenant;
  perform public.manage_platform_producer(tenant,'account',jsonb_build_object('status','active','reason','Restore test account','expectedUpdatedAt',a.updated_at));
  if exists(select 1 from public.events where producer_id=tenant and publication_state='published') then raise exception 'Restore republished events'; end if;
  snapshot:=public.platform_producer_export_snapshot(tenant);
  perform set_config('request.jwt.claims','{"aal":"aal1"}',true);
  failed:=false;
  begin perform public.platform_producer_export_snapshot(tenant); exception when others then failed:=true; end;
  if not failed then raise exception 'Unverified owner exported records'; end if;
end $$;
rollback;
