"use client";

import { useState, useTransition } from "react";
import { Flag, LoaderCircle, Plus, Trash2, X } from "lucide-react";
import { loadFinalsQualifierSetup, removeFinalsQualifier, saveFinalsQualifier } from "@/app/(app)/events/[eventId]/finals-actions";
import type { FinalsQualificationRule } from "@/lib/finals-qualifications";

const control = "h-10 max-w-full rounded-md border border-[#ccd4d0] bg-white px-3 text-sm";
export function FinalsQualifierDialog({ ropingId, name, editable }: { ropingId: string; name: string; editable: boolean }) {
  const [open, setOpen] = useState(false);
  const [data, setData] = useState<Awaited<ReturnType<typeof loadFinalsQualifierSetup>>>();
  const [pending, start] = useTransition(); const [error, setError] = useState("");
  const [id, setId] = useState<string>(); const [season, setSeason] = useState("");
  const [stage, setStage] = useState<FinalsQualificationRule["stage"]>("aggregate"); const [round, setRound] = useState(1);
  const [places, setPlaces] = useState([{ place: 1, positions: 1 }]);
  const [repeat, setRepeat] = useState<FinalsQualificationRule["repeatPolicy"]>("accumulate");
  const [ties, setTies] = useState<FinalsQualificationRule["tiePolicy"]>("all"); const [limit, setLimit] = useState(""); const [enabled, setEnabled] = useState(true);
  function reset() { setId(undefined); setStage("aggregate"); setRound(1); setPlaces([{ place: 1, positions: 1 }]); setRepeat("accumulate"); setTies("all"); setLimit(""); setEnabled(true); }
  async function load() { const next = await loadFinalsQualifierSetup(ropingId); setData(next); setSeason((current) => current || next.seasons[0]?.id || ""); }
  return <>
    <button type="button" disabled={!editable} onClick={() => { setOpen(true); setError(""); start(async () => { try { await load(); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load qualifiers."); } }); }} className="inline-flex h-9 items-center gap-2 rounded-md border border-[#d7ddda] px-3 text-xs font-semibold disabled:opacity-50"><Flag size={15} />Finals qualifier</button>
    {open && <div className="fixed inset-0 z-[85] grid place-items-center overflow-y-auto bg-black/45 p-4"><section role="dialog" aria-modal="true" aria-label={`Finals qualifier: ${name}`} className="my-6 w-full max-w-2xl rounded-md bg-white p-5 shadow-xl">
      <header className="flex justify-between gap-3"><div><h2 className="font-bold">Earned finals positions</h2><p className="mt-1 text-sm text-[#66716b]">{name}</p></div><button type="button" disabled={pending} aria-label="Close" onClick={() => setOpen(false)}><X size={20} /></button></header>
      {pending && <p role="status" className="my-4 flex items-center gap-2"><LoaderCircle className="animate-spin" size={20} />Loading or saving qualifier setup…</p>}
      {data && <fieldset disabled={pending} className="mt-5 min-w-0 space-y-5">
        {data.rules.length > 0 && <ul className="space-y-2">{data.rules.map((rule) => <li key={rule.id} className="flex flex-wrap items-center justify-between gap-2 border-b py-2 text-sm"><button type="button" className="font-semibold underline" onClick={() => { setId(rule.id); setSeason(rule.season_id); setStage(rule.stage as FinalsQualificationRule["stage"]); setRound(rule.round_number || 1); setPlaces(rule.places as { place: number; positions: number }[]); setRepeat(rule.repeat_policy as FinalsQualificationRule["repeatPolicy"]); setTies(rule.tie_policy as FinalsQualificationRule["tiePolicy"]); setLimit(rule.maximum_positions?.toString() ?? ""); setEnabled(rule.enabled); }}>{rule.stage === "go_round" ? `Round ${rule.round_number}` : rule.stage === "short_round" ? "Short round" : "Aggregate"} · {rule.enabled ? "Enabled" : "Disabled"}</button><button type="button" title="Remove qualifier rule" aria-label="Remove qualifier rule" onClick={() => { if (!window.confirm("Remove this rule? Earned positions will be recalculated; the change remains in the changelog.")) return; start(async () => { const result = await removeFinalsQualifier(ropingId, rule.id); if (result.error) setError(result.error); else { reset(); await load(); } }); }} className="p-2 text-red-700"><Trash2 size={16} /></button></li>)}</ul>}
        <div className="flex flex-wrap items-end gap-4"><label className="grid gap-2 text-sm font-semibold">Season<select className={control} value={season} onChange={(e) => setSeason(e.target.value)}><option value="">Choose season</option>{data.seasons.map((season) => <option key={season.id} value={season.id}>{season.name}</option>)}</select></label><label className="grid gap-2 text-sm font-semibold">Award from<select className={control} value={stage} onChange={(e) => setStage(e.target.value as FinalsQualificationRule["stage"])}><option value="aggregate">Aggregate</option><option value="go_round">Go round</option>{data.shortRound && <option value="short_round">Short round</option>}</select></label>{stage === "go_round" && <label className="grid gap-2 text-sm font-semibold">Round<select className={control} value={round} onChange={(e) => setRound(Number(e.target.value))}>{Array.from({ length: data.rounds }, (_, i) => <option key={i} value={i + 1}>{i + 1}</option>)}</select></label>}</div>
        <div className="space-y-3"><h3 className="text-sm font-semibold">Qualifying placements</h3>{places.map((place, i) => <div key={i} className="flex flex-wrap items-end gap-3"><label className="grid gap-1 text-xs font-semibold">Place<input type="number" min={1} max={10000} className={`${control} w-24`} value={place.place} onChange={(e) => setPlaces(places.map((value, index) => index === i ? { ...value, place: Number(e.target.value) } : value))} /></label><label className="grid gap-1 text-xs font-semibold">Positions awarded<input type="number" min={1} max={1000} className={`${control} w-28`} value={place.positions} onChange={(e) => setPlaces(places.map((value, index) => index === i ? { ...value, positions: Number(e.target.value) } : value))} /></label><button type="button" disabled={places.length === 1} title="Remove place" aria-label="Remove place" className="p-2 disabled:opacity-40" onClick={() => setPlaces(places.filter((_, index) => index !== i))}><Trash2 size={16} /></button></div>)}<button type="button" disabled={places.length >= 100} className="flex items-center gap-2 text-sm font-semibold" onClick={() => setPlaces([...places, { place: Math.max(...places.map((place) => place.place)) + 1, positions: 1 }])}><Plus size={16} />Add place</button></div>
        <div className="flex flex-wrap items-end gap-4"><label className="grid gap-2 text-sm font-semibold">Already qualified<select className={control} value={repeat} onChange={(e) => setRepeat(e.target.value as FinalsQualificationRule["repeatPolicy"])}><option value="accumulate">Earn another position</option><option value="skip">Skip; leave position unused</option><option value="pass_down">Pass to next eligible roper</option></select></label><label className="grid gap-2 text-sm font-semibold">Tied placings<select className={control} value={ties} onChange={(e) => setTies(e.target.value as FinalsQualificationRule["tiePolicy"])}><option value="all">All tied ropers qualify</option><option value="staff_decision">Hold for staff decision</option></select></label><label className="grid gap-2 text-sm font-semibold">Maximum positions per member<input className={`${control} w-36`} type="number" min={1} placeholder="Unlimited" value={limit} onChange={(e) => setLimit(e.target.value)} /></label></div>
        <label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={enabled} onChange={(e) => setEnabled(e.target.checked)} />Enabled</label>
      </fieldset>}
      {error && <p role="alert" className="mt-4 text-sm text-red-700">{error}</p>}
      <footer className="mt-5 flex flex-wrap justify-end gap-3 border-t pt-4"><button type="button" disabled={pending} className={control} onClick={reset}>New rule</button><button type="button" disabled={pending} className={control} onClick={() => setOpen(false)}>Close</button><button type="button" disabled={pending || !season || !data} className="h-10 rounded-md brand-accent-fill px-4 text-sm font-semibold text-white disabled:opacity-50" onClick={() => start(async () => { setError(""); const result = await saveFinalsQualifier(ropingId, { id, seasonId: season, stage, round: stage === "go_round" ? round : null, places, repeatPolicy: repeat, tiePolicy: ties, maximumPositions: limit ? Number(limit) : null, enabled }); if (result.error) setError(result.error); else setOpen(false); })}>Save qualifier</button></footer>
    </section></div>}
  </>;
}
