"use client";

import { PersistentForm } from "@/components/ui/persistent-form";
import { useActionState, useRef, useState, type ReactNode } from "react";
import { stockChargeAction } from "@/app/(app)/events/[eventId]/stock-charge/actions";
import { formatCurrency, formatPhoneNumber } from "@/lib/utils";
import { PhoneInput } from "@/components/ui/phone-input";

type Package = { id: string; title: string; kind: string; units: number; amount_cents: number; active: boolean };
type Session = { id: string; title: string; scheduled_date: string; arena_name: string; start_time: string | null; follows_roping_id: string | null; note: string; active: boolean };
type Roper = { id: string; first_name: string; last_name: string; phone: string | null; member_number: string };
type Purchase = { id: string; roper_id: string; title: string; kind: string; units: number; amount_cents: number; cancelled_at: string | null };
type Use = { id: string; purchase_id: string; session_id: string; reversed_at: string | null; created_at: string };
type Payment = { purchase_id: string; amount_cents: number; voided_at: string | null };
const input = "h-10 w-auto max-w-full rounded-md border border-[#cbd3ce] bg-white px-3 text-sm";
const button = "min-h-10 rounded-md bg-[#3148a5] px-4 text-sm font-semibold text-white disabled:opacity-50";

function Action({ eventId, operation, label, children }: { eventId: string; operation: string; label: string; children?: ReactNode }) {
  const request = useRef<string | null>(null);
  const [state, action, pending] = useActionState(async (state: { message?: string; success?: boolean }, form: FormData) => {
    if (operation === "purchase" || operation === "use") {
      request.current ??= crypto.randomUUID();
      form.set("requestId", request.current);
    }
    const result = await stockChargeAction(eventId, operation, state, form);
    if (result.success) request.current = null;
    return result;
  }, {});
  return <PersistentForm action={action} className="flex flex-wrap items-end gap-3">{children}<button className={button} disabled={pending}>{pending ? "Saving..." : label}</button>{state.message && <p role="status" className={`w-full text-sm ${state.success ? "text-emerald-700" : "text-red-700"}`}>{state.message}</p>}</PersistentForm>;
}
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="flex min-w-0 flex-col gap-1 text-sm font-semibold">{label}{children}</label>; }

export function StockChargeDesk({ eventId, settings, packages, sessions, ropers, purchases, payments, uses, ropings, dates, arenas, manage, collect, office, correct }: {
  eventId: string; settings: { enabled: boolean; run_limit: number | null; score_limit: number | null } | null;
  packages: Package[]; sessions: Session[]; ropers: Roper[]; purchases: Purchase[]; payments: Payment[]; uses: Use[];
  ropings: { id: string; name: string; scheduled_date: string; arena_name: string }[]; dates: string[]; arenas: string[];
  manage: boolean; collect: boolean; office: boolean; correct: boolean;
}) {
  const [search, setSearch] = useState("");
  const [newRoper, setNewRoper] = useState(false);
  const [day, setDay] = useState(dates[0]);
  const [arena, setArena] = useState(arenas[0]);
  const [listing, setListing] = useState("time");
  const [filter, setFilter] = useState("remaining");
  const [sessionId, setSessionId] = useState(sessions.find(s => s.active)?.id ?? "");
  const activeSessions = sessions.filter(s => s.active);
  const paid = new Set(payments.filter(p => !p.voided_at).map(p => p.purchase_id));
  const used = (id: string) => uses.filter(u => u.purchase_id === id && !u.reversed_at);
  const roster = new Map(ropers.map(r => [r.id, r]));
  const matches = (r: Roper) => `${r.first_name} ${r.last_name} ${r.phone ?? ""} ${r.member_number}`.toLowerCase().includes(search.toLowerCase());
  const live = purchases.filter(p => !p.cancelled_at);
  const received = payments.filter(p => !p.voided_at).reduce((n, p) => n + p.amount_cents, 0);
  const visible = live.filter(p => (filter !== "remaining" || used(p.id).length < p.units) && (filter !== "unpaid" || !paid.has(p.id)) && (!search || (roster.has(p.roper_id) && matches(roster.get(p.roper_id)!))));
  return <div className="space-y-6">
    <section className="flex flex-wrap gap-x-10 gap-y-4 border-y py-4"><div><p className="text-sm text-[#66716b]">Collected</p><p className="text-xl font-bold">{formatCurrency(received)}</p></div><div><p className="text-sm text-[#66716b]">Unpaid</p><p className="text-xl font-bold">{formatCurrency(live.filter(p => !paid.has(p.id)).reduce((n,p) => n+p.amount_cents,0))}</p></div>{["run", "score"].map(kind => <div key={kind}><p className="text-sm text-[#66716b]">{kind === "run" ? "Practice runs remaining" : "Scores remaining"}</p><p className="text-xl font-bold">{live.filter(p => p.kind === kind).reduce((n,p) => n+p.units-used(p.id).length,0)}</p></div>)}</section>
    {manage && <details className="border-b pb-4"><summary className="cursor-pointer font-bold">Stock charge setup</summary><div className="mt-4 space-y-5">
      <Action eventId={eventId} operation="settings" label="Save settings"><label className="flex min-h-10 items-center gap-2"><input type="checkbox" name="enabled" defaultChecked={settings?.enabled} />Allow stock charge runs & scores</label><Field label="Run limit per roper"><input className={input} name="runLimit" inputMode="numeric" pattern="[0-9]*" defaultValue={settings?.run_limit ?? ""} placeholder="No limit" /></Field><Field label="Score limit per roper"><input className={input} name="scoreLimit" inputMode="numeric" pattern="[0-9]*" defaultValue={settings?.score_limit ?? ""} placeholder="No limit" /></Field></Action>
      <h3 className="font-bold">Prices & packages</h3><ul className="space-y-2">{packages.map(p => <li key={p.id} className="flex flex-wrap items-center gap-3 text-sm"><span>{p.title} · {p.units} {p.kind}{p.units > 1 ? "s" : ""} · {formatCurrency(p.amount_cents)}{!p.active && " · Inactive"}</span><Action eventId={eventId} operation="package" label={p.active ? "Deactivate" : "Reactivate"}><input type="hidden" name="id" value={p.id} /><input type="hidden" name="active" value={String(!p.active)} /></Action></li>)}</ul>
      <Action eventId={eventId} operation="package" label="Add package"><Field label="Package name"><input className={input} name="title" required maxLength={100} /></Field><Field label="Type"><select className={input} name="kind"><option value="run">Practice run</option><option value="score">Score</option></select></Field><Field label="Quantity"><input className={`${input} w-20`} name="units" defaultValue="1" inputMode="numeric" pattern="[0-9]+" required /></Field><Field label="Price ($)"><input className={`${input} w-28`} name="price" inputMode="decimal" required /></Field></Action>
      <h3 className="font-bold">Add a session</h3><Action eventId={eventId} operation="session" label="Add session"><Field label="Session name"><input className={input} name="title" required maxLength={100} /></Field><Field label="Date"><select className={input} name="date" value={day} onChange={e => setDay(e.target.value)}>{dates.map(d => <option key={d}>{d}</option>)}</select></Field><Field label="Arena"><select className={input} name="arena" value={arena} onChange={e => setArena(e.target.value)}>{arenas.map(a => <option key={a}>{a}</option>)}</select></Field><Field label="Start listing"><select className={input} value={listing} onChange={e => setListing(e.target.value)}><option value="time">Set time</option><option value="follows">After a roping</option></select></Field>{listing === "time" ? <Field label="Start time"><input className={input} type="time" name="time" required /></Field> : <Field label="Follows"><select className={input} name="follows" required defaultValue=""><option value="" disabled>Choose roping</option>{ropings.filter(r => r.scheduled_date === day && r.arena_name === arena).map(r => <option key={r.id} value={r.id}>{r.name}</option>)}</select></Field>}<Field label="Note (optional)"><input className={input} name="note" maxLength={1000} /></Field></Action>
    </div></details>}
    <section><h2 className="font-bold">Sessions</h2>{sessions.length ? <ul className="mt-3 space-y-3">{sessions.map(s => <li key={s.id} className="flex flex-wrap items-center gap-3 border-b pb-3"><div><p className="font-semibold">{s.title}{!s.active && " · Inactive"}</p><p className="text-sm text-[#66716b]">{s.scheduled_date} · {s.arena_name} · {s.start_time?.slice(0,5) ?? (s.follows_roping_id ? `Follows ${ropings.find(r => r.id === s.follows_roping_id)?.name ?? "roping"}` : "Not scheduled")}</p>{s.note && <p className="text-sm">{s.note}</p>}</div>{manage && (s.start_time || s.follows_roping_id) && <Action eventId={eventId} operation="session" label={s.active ? "Close session" : "Reopen session"}><input type="hidden" name="id" value={s.id} /><input type="hidden" name="active" value={String(!s.active)} /></Action>}</li>)}</ul> : <p className="mt-2 text-sm text-[#66716b]">No sessions scheduled.</p>}</section>
    {!settings?.enabled && <p role="status" className="rounded-md bg-amber-50 p-4 text-sm font-semibold">Stock charge sales and usage are disabled for this event.</p>}
    <div className="flex flex-wrap items-center gap-3"><Field label="Find roper"><input className={input} type="search" value={search} onChange={e => setSearch(e.target.value)} placeholder="Name, number or phone" /></Field><Field label="Show"><select className={input} value={filter} onChange={e => setFilter(e.target.value)}><option value="remaining">Units remaining</option><option value="unpaid">Unpaid</option><option value="all">All purchases</option></select></Field></div>
    {office && settings?.enabled && <details className="border-y py-4"><summary className="cursor-pointer font-bold">Sell runs or scores</summary><div className="mt-4"><label className="mb-3 flex items-center gap-2 text-sm"><input type="checkbox" checked={newRoper} onChange={e => setNewRoper(e.target.checked)} />New roper</label><Action eventId={eventId} operation="purchase" label="Add purchase"><input type="hidden" name="requestId" value="" />{newRoper ? <><Field label="First name"><input className={input} name="firstName" required /></Field><Field label="Last name"><input className={input} name="lastName" required /></Field><Field label="Phone"><PhoneInput className={input} required /></Field></> : <Field label="Roper"><select className={input} name="roperId" defaultValue="" required><option value="" disabled>Choose roper</option>{ropers.filter(matches).map(r => <option key={r.id} value={r.id}>{r.first_name} {r.last_name} · {r.member_number} · {formatPhoneNumber(r.phone ?? "")}</option>)}</select></Field>}<Field label="Package"><select className={input} name="packageId" defaultValue="" required><option value="" disabled>Choose package</option>{packages.filter(p => p.active).map(p => <option key={p.id} value={p.id}>{p.title} · {formatCurrency(p.amount_cents)}</option>)}</select></Field></Action></div></details>}
    {office && <Field label="Session for marking usage"><select className={input} value={sessionId} onChange={e => setSessionId(e.target.value)}><option value="">Choose session</option>{activeSessions.map(s => <option key={s.id} value={s.id}>{s.title} · {s.arena_name} · {s.scheduled_date}</option>)}</select></Field>}
    <section className="space-y-4"><h2 className="font-bold">Purchases · {visible.length}</h2>{!visible.length && <p className="text-sm text-[#66716b]">No matching purchases.</p>}{visible.map(p => { const r = roster.get(p.roper_id); const remaining = p.units-used(p.id).length; return <article key={p.id} className="border-b pb-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-bold">{r ? `${r.first_name} ${r.last_name}` : "Roper"}</h3><p className="text-sm text-[#66716b]">{p.title} · {p.kind === "run" ? "Practice runs" : "Scores"} · {remaining} of {p.units} remaining</p></div><span className={`text-sm font-semibold ${paid.has(p.id) ? "text-emerald-700" : "text-amber-800"}`}>{formatCurrency(p.amount_cents)} · {paid.has(p.id) ? "Paid" : "Unpaid"}</span></div><div className="mt-3 flex flex-wrap gap-3">{collect && !paid.has(p.id) && <Action eventId={eventId} operation="pay" label={`Record ${formatCurrency(p.amount_cents)} received`}><input type="hidden" name="id" value={p.id} /></Action>}{office && paid.has(p.id) && remaining > 0 && settings?.enabled && sessionId && <Action eventId={eventId} operation="use" label={p.kind === "run" ? "Mark one run used" : "Mark one score used"}><input type="hidden" name="id" value={p.id} /><input type="hidden" name="sessionId" value={sessionId} /><input type="hidden" name="requestId" value="" /></Action>}</div>{correct && <details className="mt-3 text-sm"><summary className="cursor-pointer text-[#66716b]">Corrections & usage history</summary><div className="mt-3 space-y-3">{uses.filter(u => u.purchase_id === p.id).map(u => <div key={u.id}><p>{`${new Date(u.created_at).toISOString().slice(0,16).replace("T"," ")} UTC`} · {sessions.find(s => s.id === u.session_id)?.title}{u.reversed_at && " · Reversed"}</p>{!u.reversed_at && <Action eventId={eventId} operation="reverse" label="Undo usage"><input type="hidden" name="id" value={u.id} /><input className={input} name="reason" aria-label="Reason for undoing usage" placeholder="Correction reason" required minLength={5} /></Action>}</div>)}{!used(p.id).length && <Action eventId={eventId} operation="cancel" label={paid.has(p.id) ? "Record refund & cancel" : "Cancel purchase"}><input type="hidden" name="id" value={p.id} /><input className={input} name="reason" aria-label="Cancellation reason" placeholder="Reason" required minLength={5} /></Action>}</div></details>}</article>; })}</section>
  </div>;
}
