import { Download, Filter, MoreHorizontal, Plus, Search } from "lucide-react";
import { PageHeader } from "@/components/ui/page-header";
import { StatusPill } from "@/components/ui/status-pill";
import { members } from "@/data/demo";

export default function MembersPage() {
  return (
    <div className="space-y-6">
      <PageHeader title="Members" description="Manage organization memberships while each roper keeps one profile across all organizations." actions={<button className="flex h-10 items-center gap-2 rounded-md bg-[#17251f] px-4 text-sm font-semibold text-white"><Plus size={17} /> Add member</button>} />
      <div className="grid gap-3 sm:grid-cols-3"><div className="rounded-md border border-[#dfe4e1] bg-white p-4"><p className="text-xs font-semibold text-[#758078]">Active members</p><p className="mt-1 text-2xl font-bold">248</p></div><div className="rounded-md border border-[#dfe4e1] bg-white p-4"><p className="text-xs font-semibold text-[#758078]">Pending approval</p><p className="mt-1 text-2xl font-bold">7</p></div><div className="rounded-md border border-[#dfe4e1] bg-white p-4"><p className="text-xs font-semibold text-[#758078]">Expired</p><p className="mt-1 text-2xl font-bold">19</p></div></div>
      <section className="overflow-hidden rounded-md border border-[#dfe4e1] bg-white">
        <div className="flex flex-col gap-3 border-b border-[#e7ebe8] p-4 sm:flex-row sm:items-center sm:justify-between"><label className="flex h-10 max-w-md flex-1 items-center gap-2 rounded-md border border-[#d7ddda] px-3 text-[#758078]"><Search size={17} /><input className="min-w-0 flex-1 bg-transparent text-sm outline-none placeholder:text-[#99a19d]" placeholder="Search name, member number, or phone" /></label><div className="flex gap-2"><button className="flex h-10 items-center gap-2 rounded-md border border-[#d7ddda] px-3 text-sm font-semibold"><Filter size={16} /> Filter</button><button aria-label="Export members" className="grid h-10 w-10 place-items-center rounded-md border border-[#d7ddda]"><Download size={17} /></button></div></div>
        <div className="overflow-x-auto scrollbar-subtle"><table className="w-full min-w-[820px] text-left"><thead className="bg-[#f7f8f7] text-[11px] font-bold uppercase text-[#758078]"><tr><th className="px-5 py-3">Member</th><th className="px-5 py-3">Member #</th><th className="px-5 py-3">Contact</th><th className="px-5 py-3">Class</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Joined</th><th className="w-12 px-4 py-3"><span className="sr-only">Actions</span></th></tr></thead><tbody className="divide-y divide-[#e7ebe8]">{members.map((member) => <tr key={member.id} className="hover:bg-[#fafbfa]"><td className="px-5 py-4"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-full bg-[#eef1ef] text-xs font-bold text-[#435149]">{member.name.split(" ").map((part) => part[0]).join("")}</span><span className="text-sm font-semibold">{member.name}</span></div></td><td className="px-5 py-4 font-mono text-xs text-[#58645d]">{member.memberNumber}</td><td className="px-5 py-4"><p className="text-sm">{member.phone}</p><p className="mt-1 text-xs text-[#7b857f]">{member.email}</p></td><td className="px-5 py-4 text-sm">{member.classification}</td><td className="px-5 py-4"><StatusPill status={member.status} /></td><td className="px-5 py-4 text-sm text-[#66716b]">{member.joinedAt}</td><td className="px-4 py-4"><button aria-label={`Actions for ${member.name}`} className="grid h-8 w-8 place-items-center rounded-md hover:bg-[#eef1ef]"><MoreHorizontal size={18} /></button></td></tr>)}</tbody></table></div>
        <div className="flex items-center justify-between border-t border-[#e7ebe8] px-5 py-4 text-xs text-[#758078]"><span>Showing 5 of 274 members</span><div className="flex gap-2"><button className="rounded border border-[#d7ddda] px-3 py-1.5">Previous</button><button className="rounded border border-[#d7ddda] px-3 py-1.5">Next</button></div></div>
      </section>
    </div>
  );
}
