import Link from "next/link";
import { ArrowUpRight, CalendarDays, ChevronLeft, ChevronRight, Users } from "lucide-react";
import { platformAdminClient } from "@/lib/platform-admin-data";
import { healthFilters, healthQuery, type PlatformHealth } from "@/lib/platform-health";
import { AccountStatusBadge } from "@/components/platform/status-badge";

function date(value: string, timezone = "America/Chicago") {
  return new Intl.DateTimeFormat("en-US", { dateStyle: "medium", timeStyle: "short", timeZone: timezone }).format(new Date(value));
}
export default async function PlatformOverview({ searchParams }: PageProps<"/platform/overview">) {
  const filters = healthQuery(await searchParams);
  const db = await platformAdminClient();
  const { data, error } = await db.rpc("platform_account_health", { attention_filter: filters.filter, page_number: filters.page });
  if (error) throw new Error("Unable to load account health.");
  const health = data as PlatformHealth;
  const pageLink = (page: number) => `/platform/overview?${new URLSearchParams({ filter: filters.filter, page: String(page) })}`;
  return <div className="space-y-8">
    <header className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold">Account overview</h1><p className="mt-1 text-sm text-[#66716b]">Producer follow-ups and launch readiness</p></div><Link href="/platform" className="inline-flex h-10 items-center gap-2 rounded-md border border-[#ccd4d0] bg-white px-3 text-sm font-semibold"><Users size={16} />Producer accounts</Link></header>
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{(["followup","approval","setup","contact"] as const).map((key) => <Link key={key} href={`/platform/overview?filter=${key}#attention`} className="rounded-md border border-[#dfe4e1] bg-white p-4 hover:border-[#3146a8]"><p className="text-sm font-semibold text-[#66716b]">{healthFilters[key]}</p><p className="mt-2 text-2xl font-bold">{health.counts[key]}</p></Link>)}</div>
    <section id="attention" className="space-y-4 scroll-mt-4"><header className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-bold">Needs attention</h2><p className="mt-1 text-xs text-[#66716b]">Follow-ups include today, {health.today}, and earlier. Dates use Central Time.</p></div><form action="/platform/overview" className="flex flex-wrap items-end gap-2"><label className="text-xs font-semibold text-[#66716b]">Show<select name="filter" defaultValue={filters.filter} className="mt-1 block h-10 max-w-full rounded-md border border-[#ccd4d0] bg-white px-3 text-sm"><option value="">All attention</option>{Object.entries(healthFilters).map(([key,label]) => <option key={key} value={key}>{label}</option>)}</select></label><button className="h-10 rounded-md border border-[#ccd4d0] bg-white px-3 text-sm font-semibold">Apply</button></form></header>
      <div className="divide-y divide-[#dfe4e1] border-y border-[#dfe4e1]">{health.accounts.map((account) => <article key={account.id} className="flex flex-wrap items-start justify-between gap-3 py-4"><div className="min-w-0 flex-1"><Link href={`/platform/producers/${account.id}?tab=${account.needs_setup ? "onboarding" : account.needs_contact && !account.needs_approval ? "contacts" : "account"}`} className="inline-flex items-start gap-2 font-bold hover:underline">{account.name}<ArrowUpRight size={16} className="mt-1 shrink-0" /></Link><div className="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-xs font-semibold">{account.due_followup && <span className="text-[#a02c20]">{account.follow_up_on === health.today ? "Follow-up today" : "Overdue follow-up"} · {account.follow_up_on}</span>}{account.needs_setup && <span className="text-[#66716b]">{account.reviewed} of 7 onboarding reviews</span>}{account.needs_contact && <span className="text-[#a02c20]">No primary contact</span>}</div><p className="mt-2 break-words text-sm text-[#66716b]">{account.next_action || (account.needs_approval ? "Review this account for approval." : account.needs_setup ? "Continue setup review." : account.needs_contact ? "Add a primary account contact." : "Review account status.")}</p></div><AccountStatusBadge status={account.status} /></article>)}</div>
      {!health.accounts.length && <p className="py-5 text-sm text-[#66716b]">No accounts need attention in this view.</p>}
      <footer className="flex flex-wrap justify-between gap-3 text-sm text-[#66716b]"><span>{health.total} accounts · Page {filters.page}</span><div className="flex gap-4">{filters.page>1 && <Link href={pageLink(filters.page-1)} className="inline-flex items-center gap-1"><ChevronLeft size={16} />Previous</Link>}{filters.page*25<health.total && <Link href={pageLink(filters.page+1)} className="inline-flex items-center gap-1">Next<ChevronRight size={16} /></Link>}</div></footer>
    </section>
    <section className="space-y-4"><header className="flex flex-wrap items-center gap-2"><CalendarDays size={20} /><h2 className="text-lg font-bold">Events in the next 30 days</h2><span className="text-sm text-[#66716b]">{health.counts.events} scheduled or underway</span></header><div className="divide-y divide-[#dfe4e1] border-y border-[#dfe4e1]">{health.events.map((event) => <article key={event.id} className="flex flex-wrap items-start justify-between gap-3 py-4"><div className="min-w-0"><h3 className="font-semibold">{event.title}</h3><Link href={`/platform/producers/${event.producer_id}`} className="mt-1 block text-sm text-[#3146a8] hover:underline">{event.producer_name}</Link><p className="mt-1 text-sm text-[#66716b]">{date(event.starts_at,event.timezone)}{event.ends_at && ` through ${date(event.ends_at,event.timezone)}`} · {event.timezone}</p><p className="mt-1 text-xs text-[#66716b]">{event.status === "in_progress" ? "In progress" : "Scheduled"} · {event.publication_state === "published" && event.is_public ? "Public" : "Not public"}</p></div>{event.publication_state === "published" && event.is_public && <Link href={`/public/${event.producer_slug}/schedule#event-${event.id}`} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1 text-sm font-semibold underline">Public schedule<ArrowUpRight size={15} /></Link>}</article>)}</div>{!health.events.length && <p className="text-sm text-[#66716b]">No upcoming or ongoing events in this window.</p>}{health.counts.events>10 && <p className="text-xs text-[#66716b]">Showing the next 10 events. Open a producer account for their public schedule.</p>}</section>
    <section><h2 className="text-lg font-bold">Recent producer changes</h2><p className="mt-1 text-sm text-[#66716b]">Latest recorded staff change for each producer, not sign-in activity. Archived accounts are excluded.</p><div className="mt-3 divide-y divide-[#dfe4e1] border-y border-[#dfe4e1]">{health.recent.map((account) => <Link key={account.id} href={`/platform/producers/${account.id}`} className="flex flex-wrap justify-between gap-2 py-3 text-sm hover:underline"><span className="font-semibold">{account.name}</span><time className="text-[#66716b]">{date(account.last_change_at)}</time></Link>)}</div>{!health.recent.length && <p className="mt-3 text-sm text-[#66716b]">No recorded staff changes yet.</p>}</section>
  </div>;
}
