import { StatusPill } from "@/components/ui/status-pill";
import type { RoperSubmission } from "@/lib/roper-accounts";
import { OnlineEntryRequestActions } from "./online-entry-request-actions";

export function PortalSubmissions({ submissions, timezone }: { submissions: RoperSubmission[]; timezone: string }) {
  if (!submissions.length) return <p className="py-6 text-sm text-[#66716b]">No linked online entry requests yet.</p>;
  return <section aria-label="Online entry requests" className="divide-y divide-[#dfe4e1]">{submissions.map((submission) => <article key={submission.id} className="space-y-3 py-4">
    <header className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><h2 className="break-words font-semibold">{submission.eventTitle}</h2><p className="mt-1 text-xs text-[#66716b]">Submitted {new Intl.DateTimeFormat("en-US", { dateStyle: "medium", timeStyle: "short", timeZone: timezone }).format(new Date(submission.submittedAt))}</p></div><StatusPill status={submission.status} /></header>
    <ul className="space-y-2 text-sm">{submission.items.map((item, index) => <li key={`${item.name}:${item.date}:${index}`} className="break-words">{item.name}{item.division && !item.name.toLowerCase().includes(item.division.toLowerCase()) ? ` · ${item.division}` : ""} · {item.date} · {item.quantity} {item.quantity === 1 ? "entry" : "entries"}</li>)}</ul>
    <p className="text-sm text-[#66716b]">{submission.status === "waitlisted" ? "Waitlisted. No fees are due for waiting entries. Staff will contact you when a space is offered; confirmed entries are listed separately." : submission.status === "pending" ? "Awaiting producer approval. These are not confirmed entries or charges yet." : submission.status === "accepted" ? "Accepted by the producer. Confirmed entries and current fees are listed separately." : submission.status === "withdrawn" ? "Withdrawn. This request cannot be accepted by the producer." : "Declined by the producer. Contact the producer with questions."}</p>
    {submission.reviewedAt && <p className="text-xs text-[#66716b]">Reviewed {new Intl.DateTimeFormat("en-US", { dateStyle: "medium", timeStyle: "short", timeZone: timezone }).format(new Date(submission.reviewedAt))}</p>}
    {submission.producerResponse && <div className="border-l-2 border-[var(--brand-accent)] pl-3"><p className="text-xs font-semibold text-[#66716b]">Message from the producer</p><p className="mt-1 whitespace-pre-wrap break-words text-sm">{submission.producerResponse}</p></div>}
    {submission.status === "pending" && submission.canModify && submission.revision && submission.producerSlug && submission.eventSlug ? <OnlineEntryRequestActions requestId={submission.id} revision={submission.revision} producerSlug={submission.producerSlug} eventSlug={submission.eventSlug} /> : submission.status === "pending" && submission.canModify === false ? <p className="text-xs text-[#66716b]">Changes are closed. Contact the producer for assistance.</p> : null}
    {!!submission.changes?.length && <details className="text-xs text-[#66716b]"><summary className="cursor-pointer font-semibold">Request history</summary><ul className="mt-2 space-y-1">{submission.changes.map((change, index) => <li key={index}>{change.action === "edited" ? "Selections updated" : "Request withdrawn"} · {new Intl.DateTimeFormat("en-US", { dateStyle: "medium", timeStyle: "short", timeZone: timezone }).format(new Date(change.changedAt))}</li>)}</ul></details>}
  </article>)}</section>;
}
