import { Check, CircleDollarSign, GripVertical, MoreHorizontal, Plus, Settings2 } from "lucide-react";
import { PageHeader } from "@/components/ui/page-header";
import { formatCurrency } from "@/lib/utils";

const divisions = [
  { name: "Open", description: "Open to all active members and approved guests", runs: 1, maxEntries: "Unlimited", fees: [{ name: "Entry fee", cents: 5000, scope: "Per entry", included: true }, { name: "Stock fee", cents: 1000, scope: "Per entry", included: true }, { name: "Office fee", cents: 500, scope: "Once per event", included: false }] },
  { name: "#2 Division", description: "For contestants classified #2 or below", runs: 1, maxEntries: "3 per contestant", fees: [{ name: "Entry fee", cents: 4000, scope: "Per entry", included: true }, { name: "Office fee", cents: 500, scope: "Once per event", included: false }] },
  { name: "Novice", description: "Organization-approved novice contestants", runs: 2, maxEntries: "1 per contestant", fees: [{ name: "Entry fee", cents: 3000, scope: "Per entry", included: true }] },
];

export default function DivisionSettingsPage() {
  return (
    <div className="space-y-6">
      <PageHeader eyebrow="Organization setup" title="Divisions & fees" description="Build reusable division rules and fee schedules. Every setting can still be adjusted for an individual event." actions={<button className="flex h-10 items-center gap-2 rounded-md bg-[#17251f] px-4 text-sm font-semibold text-white"><Plus size={17} /> New division</button>} />
      <div className="flex gap-1 overflow-x-auto border-b border-[#d7ddda]"><button className="border-b-2 border-[#bb3e24] px-4 py-3 text-sm font-bold text-[#17201c]">Divisions</button><button className="px-4 py-3 text-sm font-semibold text-[#66716b]">Skill levels</button><button className="px-4 py-3 text-sm font-semibold text-[#66716b]">Fee library</button><button className="px-4 py-3 text-sm font-semibold text-[#66716b]">Eligibility</button></div>
      <section className="space-y-4">{divisions.map((division) => <article key={division.name} className="overflow-hidden rounded-md border border-[#dfe4e1] bg-white"><div className="flex items-start gap-3 border-b border-[#e7ebe8] p-5"><button aria-label={`Reorder ${division.name}`} className="mt-1 text-[#98a09b]"><GripVertical size={18} /></button><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-3"><h2 className="text-lg font-bold">{division.name}</h2><span className="inline-flex items-center gap-1 rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-semibold text-emerald-700"><Check size={12} /> Active</span></div><p className="mt-1 text-sm text-[#66716b]">{division.description}</p><div className="mt-3 flex flex-wrap gap-x-5 gap-y-2 text-xs font-medium text-[#758078]"><span>{division.runs} run{division.runs > 1 ? "s" : ""}</span><span>{division.maxEntries}</span><span>Guests allowed</span></div></div><button aria-label={`Options for ${division.name}`} className="grid h-9 w-9 place-items-center rounded-md border border-[#d7ddda]"><MoreHorizontal size={18} /></button></div><div className="p-5"><div className="mb-3 flex items-center justify-between"><p className="flex items-center gap-2 text-xs font-bold uppercase text-[#66716b]"><CircleDollarSign size={15} /> Default fees</p><button className="flex items-center gap-1.5 text-xs font-semibold text-[#a83720]"><Plus size={14} /> Add fee</button></div><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left"><thead className="text-[10px] font-bold uppercase text-[#8a938e]"><tr><th className="pb-2">Fee</th><th className="pb-2">Amount</th><th className="pb-2">Applied</th><th className="pb-2">Display</th><th className="w-10 pb-2"></th></tr></thead><tbody className="divide-y divide-[#edf0ee]">{division.fees.map((fee) => <tr key={fee.name}><td className="py-3 text-sm font-semibold">{fee.name}</td><td className="py-3 text-sm">{formatCurrency(fee.cents)}</td><td className="py-3 text-sm text-[#66716b]">{fee.scope}</td><td className="py-3 text-sm text-[#66716b]">{fee.included ? "Included in entry price" : "Listed separately"}</td><td className="py-3"><button aria-label={`Edit ${fee.name}`}><Settings2 size={15} className="text-[#758078]" /></button></td></tr>)}</tbody></table></div></div></article>)}</section>
      <div className="rounded-md border border-dashed border-[#cbd2ce] p-5 text-center"><p className="text-sm font-semibold">Division templates are organization-specific</p><p className="mt-1 text-xs text-[#758078]">Changes here become defaults for new ropings and do not alter past events.</p></div>
    </div>
  );
}
