"use client";
import { PersistentForm } from "@/components/ui/persistent-form";
import { useActionState, useState } from "react";
import { awardManualFinalsPosition, revokeManualFinalsPosition } from "@/app/(app)/settings/finals/actions";
import { LoaderCircle } from "lucide-react";
const input = "h-10 max-w-full rounded-md border border-[#ccd4d0] bg-white px-3 text-sm";
export function ManualFinalsAward({ seasonId, members, classes, date }: { seasonId: string; members: { id: string; name: string; number: string }[]; classes: { id: string; name: string }[]; date: string }) {
  const [state, action, pending] = useActionState(awardManualFinalsPosition, {});
  const [search, setSearch] = useState("");
  const options = members.filter((member) => `${member.name} ${member.number}`.toLowerCase().includes(search.toLowerCase())).slice(0, 100);
  return <details className="border-y py-4"><summary className="cursor-pointer text-sm font-semibold">Award positions manually</summary><PersistentForm action={action} className="mt-4 space-y-4"><input name="seasonId" type="hidden" value={seasonId} /><fieldset disabled={pending} className="flex flex-wrap items-end gap-4"><label className="grid gap-2 text-sm font-semibold">Find member<input className={`${input} w-52`} type="search" value={search} onChange={(e) => setSearch(e.target.value)} /></label><label className="grid gap-2 text-sm font-semibold">Member<select className={input} name="memberId" required><option value="">Choose member</option>{options.map((member) => <option key={member.id} value={member.id}>{member.name} · {member.number}</option>)}</select></label><label className="grid gap-2 text-sm font-semibold">Finals class<select className={input} name="classId" required><option value="">Choose class</option>{classes.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="grid gap-2 text-sm font-semibold">Award date<input className={input} name="date" type="date" defaultValue={date} required /></label><label className="grid gap-2 text-sm font-semibold">Positions<input className={`${input} w-24`} type="number" name="positions" min={1} max={1000} defaultValue={1} required /></label><label className="grid gap-2 text-sm font-semibold">Reason<input className={`${input} w-96`} name="reason" minLength={5} maxLength={2000} required /></label><button className="flex h-10 items-center gap-2 rounded-md brand-accent-fill px-4 text-sm font-semibold text-white">{pending && <LoaderCircle size={16} className="animate-spin" />}Award positions</button></fieldset>{state.error && <p role="alert" className="text-sm text-red-700">{state.error}</p>}{state.success && <p role="status" className="text-sm text-emerald-700">Positions awarded and recorded in the changelog.</p>}</PersistentForm></details>;
}
export function RevokeFinalsAward({ awardId }: { awardId: string }) {
  const [state, action, pending] = useActionState(revokeManualFinalsPosition, {});
  return <details><summary className="cursor-pointer text-sm font-semibold text-red-700">Revoke</summary><PersistentForm action={action} className="mt-2 flex flex-wrap gap-2"><input type="hidden" name="awardId" value={awardId} /><input name="reason" required minLength={5} maxLength={2000} aria-label="Revocation reason" placeholder="Reason for revocation" className={`${input} w-64`} /><button disabled={pending} className="rounded-md border border-red-200 px-3 text-sm text-red-700">Confirm revocation</button>{state.error && <p role="alert" className="text-sm text-red-700">{state.error}</p>}</PersistentForm></details>;
}
